apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otp-sms-platform.fullname" . }}-secrets
  labels:
    {{- include "otp-sms-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  jasmin-user: "otp_api"
  jasmin-password: "otp_api_secret"
  admin-token: "otp-admin-secret"
