{{- if .Values.billingService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otp-sms-platform.fullname" . }}-billing-service
  labels:
    {{- include "otp-sms-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: billing-service
spec:
  {{- if not .Values.billingService.autoscaling.enabled }}
  replicas: {{ .Values.billingService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otp-sms-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: billing-service
  template:
    metadata:
      labels:
        {{- include "otp-sms-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: billing-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: billing-service
        image: "{{ .Values.billingService.image.repository }}:{{ .Values.billingService.image.tag }}"
        imagePullPolicy: {{ .Values.billingService.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: BILLING_PORT
          value: "8081"
        - name: BILLING_DB_URL
          value: {{ include "otp-sms-platform.postgresql.asyncpgUrl" . | quote }}
        - name: BILLING_DB_POOL_MIN
          value: {{ .Values.billingService.config.dbPoolMin | quote }}
        - name: BILLING_DB_POOL_MAX
          value: {{ .Values.billingService.config.dbPoolMax | quote }}
        - name: BILLING_JASMIN_AMQP_HOST
          value: {{ tpl .Values.billingService.config.amqpHost . | quote }}
        - name: BILLING_JASMIN_AMQP_USER
          value: {{ .Values.rabbitmq.auth.username | quote }}
        - name: BILLING_JASMIN_AMQP_PASSWORD
          value: {{ .Values.rabbitmq.auth.password | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.billingService.resources | nindent 10 }}
{{- end }}
