{{- if and .Values.apiGateway.enabled .Values.apiGateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "otp-sms-platform.fullname" . }}-api-gateway
  labels:
    {{- include "otp-sms-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with .Values.apiGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiGateway.ingress.className }}
  ingressClassName: {{ .Values.apiGateway.ingress.className }}
  {{- end }}
  {{- if .Values.apiGateway.ingress.tls }}
  tls:
    {{- range .Values.apiGateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiGateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "otp-sms-platform.fullname" $ }}-api-gateway
                port:
                  number: {{ $.Values.apiGateway.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
