{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otp-sms-platform.fullname" . }}-api-gateway
  labels:
    {{- include "otp-sms-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "otp-sms-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
